# Generated by Django 4.0.1 on 2022-02-01 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner', models.FileField(blank=True, upload_to='', verbose_name='Баннер в шапке')),
                ('title', models.CharField(blank=True, max_length=50, verbose_name='Заголовок раздела')),
                ('subtitle', models.CharField(blank=True, max_length=50, verbose_name='Подзаголовок раздела')),
                ('bottom_title', models.CharField(blank=True, max_length=50, verbose_name='Заголовок ниженго блока')),
                ('bottom_text', models.CharField(blank=True, max_length=2000, verbose_name='Текст ниженго блока')),
            ],
            options={
                'verbose_name': 'Раздел "Проекты"',
                'verbose_name_plural': 'Раздел "Проекты"',
            },
        ),
        migrations.CreateModel(
            name='ProjectSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(blank=True, max_length=50, verbose_name='Секция')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Названме проекта')),
                ('description', models.CharField(blank=True, max_length=100, verbose_name=' Краткое описание')),
                ('image', models.FileField(blank=True, upload_to='', verbose_name='Изображение')),
                ('section', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='projects.projectpage', verbose_name='Секция')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
            },
        ),
    ]
