# Generated by Django 4.0.1 on 2022-02-01 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectdetail',
            name='slug',
            field=models.SlugField(default='', max_length=100, unique=True),
        ),
    ]
