# Generated by Django 4.0.1 on 2022-02-01 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_projectdetail_prefix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectdetail',
            name='name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Название проекта'),
        ),
        migrations.AlterField(
            model_name='projectdetail',
            name='section',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='projects.projectsection', verbose_name='Секция'),
        ),
    ]
