# Generated by Django 4.0.1 on 2022-02-01 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_projectdetail_name_alter_projectdetail_section'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectsection',
            options={'verbose_name': 'Секция для проекта', 'verbose_name_plural': 'Секции для проектов'},
        ),
        migrations.AlterField(
            model_name='projectdetail',
            name='prefix',
            field=models.CharField(blank=True, max_length=7, verbose_name='Префикс для фильтра'),
        ),
    ]
