# Generated by Django 4.0.1 on 2022-02-02 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_projectsection_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectdetail',
            name='prefix',
        ),
        migrations.AddField(
            model_name='projectsection',
            name='prefix',
            field=models.CharField(blank=True, max_length=7, verbose_name='Префикс для фильтра'),
        ),
    ]
