# Generated by Django 4.0.1 on 2022-02-02 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_remove_projectdetail_prefix_projectsection_prefix'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectsection',
            name='prefix',
        ),
        migrations.AddField(
            model_name='projectdetail',
            name='prefix',
            field=models.CharField(blank=True, max_length=7, verbose_name='Префикс для фильтра'),
        ),
    ]
