# Generated by Django 4.0.1 on 2022-02-03 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_remove_projectsection_prefix_projectdetail_prefix'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectsection',
            options={'verbose_name': 'Категория проекта', 'verbose_name_plural': 'Категории проектов'},
        ),
        migrations.AddField(
            model_name='projectdetail',
            name='article_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Название статьи'),
        ),
        migrations.AddField(
            model_name='projectdetail',
            name='article_photo',
            field=models.FileField(blank=True, upload_to='', verbose_name='Фото в статье'),
        ),
        migrations.AddField(
            model_name='projectdetail',
            name='article_text',
            field=models.CharField(blank=True, max_length=100, verbose_name='Текст статьи'),
        ),
        migrations.AddField(
            model_name='projectdetail',
            name='gallery_1',
            field=models.FileField(blank=True, upload_to='', verbose_name='Фото 1 в галерее'),
        ),
        migrations.AddField(
            model_name='projectdetail',
            name='gallery_2',
            field=models.FileField(blank=True, upload_to='', verbose_name='Фото 2 в галерее'),
        ),
        migrations.AddField(
            model_name='projectdetail',
            name='gallery_3',
            field=models.FileField(blank=True, upload_to='', verbose_name='Фото 3 в галерее'),
        ),
        migrations.AddField(
            model_name='projectdetail',
            name='gallery_4',
            field=models.FileField(blank=True, upload_to='', verbose_name='Фото 4 в галерее'),
        ),
        migrations.AddField(
            model_name='projectdetail',
            name='gallery_5',
            field=models.FileField(blank=True, upload_to='', verbose_name='Фото 5 в галерее'),
        ),
        migrations.AddField(
            model_name='projectdetail',
            name='gallery_6',
            field=models.FileField(blank=True, upload_to='', verbose_name='Фото 6 в галерее'),
        ),
        migrations.AlterField(
            model_name='projectdetail',
            name='image',
            field=models.FileField(blank=True, upload_to='', verbose_name='Фото для входа в проект'),
        ),
    ]
