# Generated by Django 4.0.1 on 2022-02-03 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_remove_projectdetail_prefix'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectsection',
            name='alias',
            field=models.CharField(blank=True, max_length=50, verbose_name='Сокращение'),
        ),
    ]
