# Generated by Django 4.0.1 on 2022-02-03 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_projectsection_alias'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectdetail',
            name='article_thumb',
            field=models.FileField(blank=True, upload_to='', verbose_name='Эскиз 277*139'),
        ),
        migrations.AlterField(
            model_name='projectdetail',
            name='article_photo',
            field=models.FileField(blank=True, upload_to='', verbose_name='Фото в статье 730*460'),
        ),
        migrations.AlterField(
            model_name='projectdetail',
            name='article_text',
            field=models.CharField(blank=True, max_length=2000, verbose_name='Текст статьи'),
        ),
    ]
