# Generated by Django 4.0.1 on 2022-02-03 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_projectdetail_article_thumb_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectsection',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=100),
        ),
    ]
