# Generated by Django 4.0.1 on 2022-02-03 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_projectsection_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectsection',
            name='slug',
            field=models.SlugField(default='', max_length=100, unique=True),
        ),
    ]
