# Generated by Django 4.0.1 on 2022-02-03 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_alter_projectsection_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectdetail',
            name='gallery_1',
        ),
        migrations.RemoveField(
            model_name='projectdetail',
            name='gallery_2',
        ),
        migrations.RemoveField(
            model_name='projectdetail',
            name='gallery_3',
        ),
        migrations.RemoveField(
            model_name='projectdetail',
            name='gallery_4',
        ),
        migrations.RemoveField(
            model_name='projectdetail',
            name='gallery_5',
        ),
        migrations.RemoveField(
            model_name='projectdetail',
            name='gallery_6',
        ),
    ]
