# Generated by Django 4.0.1 on 2022-02-03 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_remove_projectdetail_gallery_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectdetail',
            name='article_thumb',
            field=models.FileField(blank=True, upload_to='', verbose_name='Эскиз фото в статье 277*139'),
        ),
    ]
