# Generated by Django 4.0.1 on 2022-02-09 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_alter_projectdetail_article_photo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndProjectPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner', models.FileField(blank=True, upload_to='banners', verbose_name='Баннер в шапке 1600*235')),
                ('title', models.CharField(blank=True, max_length=50, verbose_name='Заголовок раздела')),
                ('subtitle', models.CharField(blank=True, max_length=50, verbose_name='Подзаголовок раздела')),
                ('text_title', models.CharField(blank=True, max_length=50, verbose_name='Заголовок')),
                ('text', models.CharField(blank=True, max_length=2000, verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Раздел "Проекты"',
                'verbose_name_plural': 'Раздел "Проекты"',
            },
        ),
    ]
