# Generated by Django 4.0.1 on 2022-02-01 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_1', models.FileField(blank=True, upload_to='', verbose_name='Фото 1, 1110*534')),
                ('thumb_1', models.FileField(blank=True, upload_to='', verbose_name='Эскиз 1, 177*107')),
                ('image_2', models.FileField(blank=True, upload_to='', verbose_name='Фото 2, 1110*534')),
                ('thumb_2', models.FileField(blank=True, upload_to='', verbose_name='Эскиз 2, 177*107')),
                ('image_3', models.FileField(blank=True, upload_to='', verbose_name='Фото 3, 1110*534')),
                ('thumb_3', models.FileField(blank=True, upload_to='', verbose_name='Эскиз 3, 177*107')),
                ('image_4', models.FileField(blank=True, upload_to='', verbose_name='Фото 4, 1110*534')),
                ('thumb_4', models.FileField(blank=True, upload_to='', verbose_name='Эскиз 4, 177*107')),
                ('image_5', models.FileField(blank=True, upload_to='', verbose_name='Фото 5, 1110*534')),
                ('thumb_5', models.FileField(blank=True, upload_to='', verbose_name='Эскиз 5, 177*107')),
                ('image_6', models.FileField(blank=True, upload_to='', verbose_name='Фото 6, 1110*534')),
                ('thumb_6', models.FileField(blank=True, upload_to='', verbose_name='Эскиз 6, 177*107')),
                ('image_7', models.FileField(blank=True, upload_to='', verbose_name='Фото 7, 1110*534')),
                ('thumb_7', models.FileField(blank=True, upload_to='', verbose_name='Эскиз 7, 177*107')),
                ('image_8', models.FileField(blank=True, upload_to='', verbose_name='Фото 8, 1110*534')),
                ('thumb_8', models.FileField(blank=True, upload_to='', verbose_name='Эскиз 8, 177*107')),
                ('image_9', models.FileField(blank=True, upload_to='', verbose_name='Фото 9, 1110*534')),
                ('thumb_9', models.FileField(blank=True, upload_to='', verbose_name='Эскиз 9, 177*107')),
                ('image_10', models.FileField(blank=True, upload_to='', verbose_name='Фото 10, 1110*534')),
                ('thumb_10', models.FileField(blank=True, upload_to='', verbose_name='Эскиз 10, 177*107')),
            ],
            options={
                'verbose_name': 'Фото галереи',
                'verbose_name_plural': 'Фото галереи',
            },
        ),
        migrations.CreateModel(
            name='GalleryPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner', models.FileField(blank=True, upload_to='', verbose_name='Баннер в шапке')),
                ('title', models.CharField(blank=True, max_length=50, verbose_name='Заголовок раздела')),
                ('subtitle', models.CharField(blank=True, max_length=50, verbose_name='Подзаголовок раздела')),
                ('bottom_title', models.CharField(blank=True, max_length=50, verbose_name='Заголовок ниженго блока')),
                ('bottom_text', models.CharField(blank=True, max_length=2000, verbose_name='Текст ниженго блока')),
            ],
            options={
                'verbose_name': 'Раздел "Галерея"',
                'verbose_name_plural': 'Раздел "Галерея"',
            },
        ),
    ]
