# Generated by Django 4.0.1 on 2022-02-01 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallerydetail',
            name='image_1',
        ),
        migrations.RemoveField(
            model_name='gallerydetail',
            name='image_10',
        ),
        migrations.RemoveField(
            model_name='gallerydetail',
            name='image_2',
        ),
        migrations.RemoveField(
            model_name='gallerydetail',
            name='image_3',
        ),
        migrations.RemoveField(
            model_name='gallerydetail',
            name='image_4',
        ),
        migrations.RemoveField(
            model_name='gallerydetail',
            name='image_5',
        ),
        migrations.RemoveField(
            model_name='gallerydetail',
            name='image_6',
        ),
        migrations.RemoveField(
            model_name='gallerydetail',
            name='image_7',
        ),
        migrations.RemoveField(
            model_name='gallerydetail',
            name='image_8',
        ),
        migrations.RemoveField(
            model_name='gallerydetail',
            name='image_9',
        ),
        migrations.RemoveField(
            model_name='gallerydetail',
            name='thumb_1',
        ),
        migrations.RemoveField(
            model_name='gallerydetail',
            name='thumb_10',
        ),
        migrations.RemoveField(
            model_name='gallerydetail',
            name='thumb_2',
        ),
        migrations.RemoveField(
            model_name='gallerydetail',
            name='thumb_3',
        ),
        migrations.RemoveField(
            model_name='gallerydetail',
            name='thumb_4',
        ),
        migrations.RemoveField(
            model_name='gallerydetail',
            name='thumb_5',
        ),
        migrations.RemoveField(
            model_name='gallerydetail',
            name='thumb_6',
        ),
        migrations.RemoveField(
            model_name='gallerydetail',
            name='thumb_7',
        ),
        migrations.RemoveField(
            model_name='gallerydetail',
            name='thumb_8',
        ),
        migrations.RemoveField(
            model_name='gallerydetail',
            name='thumb_9',
        ),
        migrations.AddField(
            model_name='gallerydetail',
            name='image',
            field=models.FileField(blank=True, upload_to='', verbose_name='Фото, 1110*534'),
        ),
        migrations.AddField(
            model_name='gallerydetail',
            name='thumb',
            field=models.FileField(blank=True, upload_to='', verbose_name='Эскиз, 177*107'),
        ),
    ]
