# Generated by Django 4.0.1 on 2022-02-05 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_remove_gallerydetail_image_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallerypage',
            name='banner',
            field=models.FileField(blank=True, upload_to='', verbose_name='Баннер в шапке 1600*235'),
        ),
    ]
