# Generated by Django 4.0.1 on 2022-02-05 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_alter_gallerypage_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallerydetail',
            name='image_title',
            field=models.CharField(blank=True, max_length=50, verbose_name='Подпись к фото'),
        ),
    ]
