# Generated by Django 4.0.1 on 2022-02-08 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_gallerydetail_image_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallerydetail',
            name='image',
            field=models.FileField(blank=True, upload_to='gallery', verbose_name='Фото, 1110*534'),
        ),
        migrations.AlterField(
            model_name='gallerydetail',
            name='image_title',
            field=models.CharField(blank=True, max_length=100, verbose_name='Подпись к фото'),
        ),
        migrations.AlterField(
            model_name='gallerydetail',
            name='thumb',
            field=models.FileField(blank=True, upload_to='gallery', verbose_name='Эскиз, 177*107'),
        ),
        migrations.AlterField(
            model_name='gallerypage',
            name='banner',
            field=models.FileField(blank=True, upload_to='banners', verbose_name='Баннер в шапке 1600*235'),
        ),
    ]
