# Generated by Django 4.0.1 on 2022-02-03 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='banner',
            field=models.FileField(blank=True, upload_to='', verbose_name='Баннер в шапке'),
        ),
    ]
