# Generated by Django 4.0.1 on 2022-02-05 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_contact_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactform',
            name='file',
            field=models.FileField(blank=True, upload_to='userfiles', verbose_name='Прикрепленный файл'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='banner',
            field=models.FileField(blank=True, upload_to='', verbose_name='Баннер в шапке 1600*235'),
        ),
    ]
