# Generated by Django 4.0.1 on 2022-02-08 08:13

import contact.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_contactform_file_alter_contact_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='banner',
            field=models.FileField(blank=True, upload_to='banners', verbose_name='Баннер в шапке 1600*235'),
        ),
        migrations.AlterField(
            model_name='contactform',
            name='file',
            field=models.FileField(blank=True, default='', upload_to='uploads', validators=[contact.models.validate_file_extension, contact.models.validate_file_size], verbose_name='Баннер в шапке 1600*235'),
        ),
    ]
