# Generated by Django 4.0.1 on 2022-01-28 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServicePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_title', models.CharField(blank=True, max_length=50, verbose_name='Название услуги')),
                ('service_text', models.CharField(blank=True, max_length=150, verbose_name='Описание услуги')),
                ('title', models.CharField(blank=True, max_length=50, verbose_name='Заголовок раздела')),
                ('subtitle', models.CharField(blank=True, max_length=50, verbose_name='Подзаголовок раздела')),
                ('text', models.CharField(blank=True, max_length=350, verbose_name='Текст')),
                ('image', models.FileField(blank=True, upload_to='', verbose_name='Фото')),
                ('bottom_title', models.CharField(blank=True, max_length=50, verbose_name='Заголовок ниженго блока')),
                ('bottom_text', models.CharField(blank=True, max_length=150, verbose_name='Теекст ниженго блока')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
            },
        ),
    ]
