# Generated by Django 4.0.1 on 2022-01-28 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_servicepage_bottom_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicepage',
            name='service_image_1',
            field=models.FileField(blank=True, upload_to='', verbose_name='Изображение 1'),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='service_image_2',
            field=models.FileField(blank=True, upload_to='', verbose_name='Изображение 2'),
        ),
        migrations.AlterField(
            model_name='servicepage',
            name='text',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Текст'),
        ),
    ]
