# Generated by Django 4.0.1 on 2022-01-30 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_servicedetail_alter_servicepage_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicedetail',
            old_name='service_title',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='servicedetail',
            name='service_image_1',
        ),
        migrations.RemoveField(
            model_name='servicedetail',
            name='service_image_2',
        ),
        migrations.RemoveField(
            model_name='servicedetail',
            name='service_text',
        ),
        migrations.AddField(
            model_name='servicedetail',
            name='icon_1',
            field=models.FileField(blank=True, upload_to='', verbose_name='Иконка 1'),
        ),
        migrations.AddField(
            model_name='servicedetail',
            name='icon_2',
            field=models.FileField(blank=True, upload_to='', verbose_name='Иконка 2'),
        ),
        migrations.AddField(
            model_name='servicedetail',
            name='image_1',
            field=models.FileField(blank=True, upload_to='', verbose_name='Фото 1'),
        ),
        migrations.AddField(
            model_name='servicedetail',
            name='image_10',
            field=models.FileField(blank=True, upload_to='', verbose_name='Фото 10'),
        ),
        migrations.AddField(
            model_name='servicedetail',
            name='image_2',
            field=models.FileField(blank=True, upload_to='', verbose_name='Фото 2'),
        ),
        migrations.AddField(
            model_name='servicedetail',
            name='image_3',
            field=models.FileField(blank=True, upload_to='', verbose_name='Фото 3'),
        ),
        migrations.AddField(
            model_name='servicedetail',
            name='image_4',
            field=models.FileField(blank=True, upload_to='', verbose_name='Фото 4'),
        ),
        migrations.AddField(
            model_name='servicedetail',
            name='image_5',
            field=models.FileField(blank=True, upload_to='', verbose_name='Фото 5'),
        ),
        migrations.AddField(
            model_name='servicedetail',
            name='image_6',
            field=models.FileField(blank=True, upload_to='', verbose_name='Фото 6'),
        ),
        migrations.AddField(
            model_name='servicedetail',
            name='image_7',
            field=models.FileField(blank=True, upload_to='', verbose_name='Фото 7'),
        ),
        migrations.AddField(
            model_name='servicedetail',
            name='image_8',
            field=models.FileField(blank=True, upload_to='', verbose_name='Фото 8'),
        ),
        migrations.AddField(
            model_name='servicedetail',
            name='image_9',
            field=models.FileField(blank=True, upload_to='', verbose_name='Фото 9'),
        ),
        migrations.AddField(
            model_name='servicedetail',
            name='short_description',
            field=models.CharField(blank=True, max_length=250, verbose_name='Краткое описание'),
        ),
        migrations.AddField(
            model_name='servicedetail',
            name='slug',
            field=models.SlugField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='servicedetail',
            name='text_1',
            field=models.CharField(blank=True, max_length=2000, verbose_name='Первый текст'),
        ),
        migrations.AddField(
            model_name='servicedetail',
            name='text_2',
            field=models.CharField(blank=True, max_length=2000, verbose_name='Второй текст'),
        ),
        migrations.AddField(
            model_name='servicedetail',
            name='title_1',
            field=models.CharField(blank=True, max_length=50, verbose_name='Название первого текста'),
        ),
        migrations.AddField(
            model_name='servicedetail',
            name='title_2',
            field=models.CharField(blank=True, max_length=50, verbose_name='Название второго текста'),
        ),
    ]
