# Generated by Django 4.0.1 on 2022-01-30 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_rename_service_title_servicedetail_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicedetail',
            name='slug',
            field=models.SlugField(max_length=80, unique=True),
        ),
    ]
