# Generated by Django 4.0.1 on 2022-01-30 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_alter_servicedetail_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicedetail',
            name='banner',
            field=models.FileField(blank=True, upload_to='', verbose_name='Баннер'),
        ),
    ]
