# Generated by Django 4.0.1 on 2022-01-30 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_servicedetail_thumb_1_servicedetail_thumb_10_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicedetail',
            name='banner',
            field=models.FileField(blank=True, upload_to='', verbose_name='Баннер в шапке'),
        ),
        migrations.AlterField(
            model_name='servicedetail',
            name='name',
            field=models.CharField(blank=True, max_length=50, verbose_name='Услуга'),
        ),
        migrations.AlterField(
            model_name='servicedetail',
            name='short_description',
            field=models.CharField(blank=True, max_length=125, verbose_name='Краткое описание'),
        ),
    ]
