# Generated by Django 4.0.1 on 2022-02-05 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_alter_servicedetail_banner_alter_servicedetail_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicedetail',
            name='banner',
            field=models.FileField(blank=True, upload_to='', verbose_name='Баннер в шапке 1600*235'),
        ),
        migrations.AlterField(
            model_name='servicedetail',
            name='icon_1',
            field=models.FileField(blank=True, upload_to='', verbose_name='Иконка цветная 81*80'),
        ),
        migrations.AlterField(
            model_name='servicedetail',
            name='icon_2',
            field=models.FileField(blank=True, upload_to='', verbose_name='Иконка белая 81*80'),
        ),
        migrations.AlterField(
            model_name='servicepage',
            name='image',
            field=models.FileField(blank=True, upload_to='', verbose_name='Фото 880*548'),
        ),
    ]
