# Generated by Django 4.0.1 on 2022-01-27 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, verbose_name='Заголовок')),
                ('subtitle', models.CharField(blank=True, max_length=50, verbose_name='Подзаголовок')),
                ('text', models.CharField(blank=True, max_length=700, verbose_name='Заголовок')),
                ('image', models.FileField(blank=True, upload_to='', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Кратко о нас',
                'verbose_name_plural': 'Кратко о нас',
            },
        ),
    ]
