# Generated by Django 4.0.1 on 2022-01-27 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, verbose_name='Заголовок')),
                ('subtitle', models.CharField(blank=True, max_length=70, verbose_name='Подзаголовок')),
                ('text', models.CharField(blank=True, max_length=750, verbose_name='Текст')),
                ('service_image_1', models.FileField(blank=True, upload_to='', verbose_name='Изображение 1')),
                ('service_image_2', models.FileField(blank=True, upload_to='', verbose_name='Изображение 2')),
                ('service_title', models.CharField(blank=True, max_length=50, verbose_name='Название услуги')),
                ('service_text', models.CharField(blank=True, max_length=100, verbose_name='О сервисе')),
                ('link_text', models.CharField(blank=True, max_length=20, verbose_name='Текст ссылки')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
            },
        ),
        migrations.AlterField(
            model_name='about',
            name='text',
            field=models.CharField(blank=True, max_length=750, verbose_name='Текст'),
        ),
    ]
