# Generated by Django 4.0.1 on 2022-01-28 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_service_alter_about_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='subtitle',
            field=models.CharField(blank=True, max_length=70, verbose_name='Подзаголовок раздела'),
        ),
        migrations.AlterField(
            model_name='service',
            name='text',
            field=models.CharField(blank=True, max_length=750, verbose_name='Текст раздела'),
        ),
        migrations.AlterField(
            model_name='service',
            name='title',
            field=models.CharField(blank=True, max_length=50, verbose_name='Заголовок раздела'),
        ),
    ]
