# Generated by Django 4.0.1 on 2022-02-08 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_about_image_alter_head_image_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='image',
            field=models.FileField(blank=True, upload_to='home', verbose_name='Изображение 660*600'),
        ),
        migrations.AlterField(
            model_name='head',
            name='image_1',
            field=models.FileField(blank=True, upload_to='home', verbose_name='Первый слайд 1920*1280'),
        ),
        migrations.AlterField(
            model_name='head',
            name='image_2',
            field=models.FileField(blank=True, upload_to='home', verbose_name='Второй слайд 1920*1280'),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_image_1',
            field=models.FileField(blank=True, upload_to='icons', verbose_name='Иконка цветная 48*48'),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_image_2',
            field=models.FileField(blank=True, upload_to='icons', verbose_name='Иконка белая 48*48'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='image',
            field=models.FileField(blank=True, upload_to='home', verbose_name='Картинка 160*205'),
        ),
    ]
